### ISSUE TITLE
not scraping artwork!

### ISSUE THREAD

**Issue by pingutm** [HoraceAndTheSpider/UAGS#1]
im trying to scrape my amiga collection on retropie

i am running with command "sudo python3 UAGS.py"

while it scrapes the titles ok it is not saving ANY artwork to snaps,wheel etc and i cannot see them being saved to anywhere else

is it broken or am i doing something wrong?

**Comment by HoraceAndTheSpider** [comment]
Bizarre... I will have to check!
Could be that something has changed with openretro.org

**Comment by HoraceAndTheSpider** [comment]
Change to the website, as expected. New fix should be a little more resistant!

All working here. :)

**Comment by ransom1122** [comment]
I have been scanning almost 200 entries and its taken about over an hour? Going by this speed, it will take over 24hours to scan the 1600 games in your download packs. 

Is this normal?

The other problem is when it prompts you to choose a game because of duplicate words, you have to manually choose these otherwise the process stops until you press either 1, 2 or 3 correcting which game the cover is for.

**Comment by HoraceAndTheSpider** [comment]
Sounds like your connection is a bit slow.

But yes, it's normal... if you download all 3 artworks then the pack does take several hours to do even on a good speed connection, because of the images. 

This is why it gives the option to "not overwrite existing" artwork, because it makes scraping much faster.

**Comment by ransom1122** [comment]
OK.
Is there a way to stop and save halfway?

I accidently pulled out the network cable during a cover download and it halted with a corrupt gamelist.xml file. The next cover download allowed me to delete the gamelist.xml file before downloading all the covers again.

I also have to scan an extra 176 CD32 games added in my Games_CD32 folder :)

**Comment by HoraceAndTheSpider** [comment]
Ctrl-C i think will force it to stop. You will not need to download all covers again if you select 'n' here: 

> HoraceAndTheSpider's openretro.org UAE4Arm Amiga Game Scraper | www.ultimateamiga.co.uk
> 
> Scrape existing game entries? (y/n) y
> All found game entries will be scraped.
> 
> Limit scanned files to a specific pattern match? (Enter pattern or leave blank) 
> 
> **Overwrite existing images**, such as in boxarts/ ? (y/n) **n**



The scanning will just look for .uae configs in /amiga/  , no need to worry about where the data files are.

**Comment by ransom1122** [comment]
Thank you once again.

**Comment by ransom1122** [comment]
After Pressing CTR+C It quits the scan like you said, When you retype python3 UAGS.py to continue to scan do you press "n" to all 3 prompts?

**Scrape existing game entries? (y/n)
Overwrite existing images, such as in boxarts/ ? (y/n)
Store Additional images to snap/and wheel/ ? (y/n)?**

If you press YES on any of these prompts the whole scan starts from the start again ignoring the skipping. If you press NO on all 3 prompts i tprompts you with Skipping games that already have covers. 

Is this correct?

Also If you press **"x"** on a cover that prompts you to either select which game, (s) to skip or **"x"** to exit. Upon Exiting will covers continue to download from this point? 

Or must we **only**  press CRT+C for the cover download to resume?

**Comment by HoraceAndTheSpider** [comment]
I am not sure I understand , sorry.

You should be aware that scraping is *not* specifically about gettting artwork. It is creating an entry for the game in gamelist.xml. The artwork is an added side -effect. 



For each option, you pick what you want.... this changes for each user, so I can't tell you what you "should" answer I'm afraid. 

"Scrape existing game entries" - yes to scrape everything, No to ignore games already scraped and in gamelist.xml

"Overwrite existing images" - yes to redownload all files, No to only download ones which do not already exist locally.

"Store additional images" yes to also download screenshots and title screens, no to only download box art.

In theory you should never use Ctrl-C anyway. I mentioned this because you seemed concerned about scraping a lot of entries. It is a fail-safe.

You should really wait until prompted and type "x" to stop the scraping process, or let it end naturally. Nothing more happens after this other than saving the gamelist.xml. 
You will reach the end   much quicker if you only scrape for "new" entries each time (answer N to question 1)

**Comment by ransom1122** [comment]
After about 3 attempts of scanning for covers on 3 given days, pressing x to exit from each scan. now I am facing a random crash error. I have tried about 10 times and it keeps crashing with same error?

here is a pic
http://i64.tinypic.com/2yv1469.jpg

Do I have to delete all and re scan everything or is there something wrong at your end?


Also Are we able to add our own covers to games that are not scraped from openretro.org somehow?

**Comment by ransom1122** [comment]
It seems the issue has now resolved itself. Scraping is working fine.

With the other question - Are we able to add our own covers to games that are not scraped from openretro.org somehow? Or even re scape from openretro no games that werent scraped correctly? Like my CD32 games some were scraped some were not.

**Comment by HoraceAndTheSpider** [comment]
Looked like an SSL issue , so there is possibly something I can do to improve that.

For adding covers, go onto openretro.org and submit some! The reason for using that source is because anyone can submit to it (including custom covers for PD games etc)

It will use HOL.abime.Net as a "fall back" if no cover is found , but if both are blank there probably isn't one
