### ISSUE TITLE
Scraping artwork for only a single game

### ISSUE THREAD

**Issue by ransom1122** [HoraceAndTheSpider/UAGS#3]
Hi,

I would like to know how I can scan a single game added in Emulation station using UAGS.

I see once you begin Python3 UAGS.py after the 1st prompt (y or n) I think you can force it to scan a game there possible by typing **3D World Boxing*** or something in those lines?

Game is 3D World Boxing (1992)(Simulmondo)(M4)[cr SKR][t +5 GOD].adf

Entered into as **3D World Boxing [ADF].zip**

I can't let the system Rescan my 2750 Scans again, because it seems to auto download covers that are already there, like Captain Planet, etc, also gets confused on each entry of my 150 Official CD32 games I have added, which all takes a long time to say **ignore** on each prompt. Just takes so much time.

I managed to edit the gamelist.xml with notepad++ and entered everything manually like this, but that takes a very long time..
![20170603_164419_resized](https://cloud.githubusercontent.com/assets/28079950/26751418/6da1ff8e-487c-11e7-813d-6c0a9d99a849.jpg)

**Comment by HoraceAndTheSpider** [comment]
Hi.

Just type "3D world boxing" when prompted about limited scanning.

There is no need to re download artwork/box set you already have. One of the options asks you about this and you need to select "n"

I can't say what the options are exactly because I don't have the screen in front of me right now.

Sent from my iPhone

On 3 Jun 2017, at 07:13, ransom1122 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I would like to know how I can scan a single game added in Emulation station using UAGS.

I see once you begin Python3 UAGS.py after the 1st prompt (y or n) I think you can force it to scan a game there possible by typing 3D World Boxing* or something in those lines?

Game is 3D World Boxing (1992)(Simulmondo)(M4)[cr SKR][t +5 GOD].adf

Entered into as 3D World Boxing [ADF].zip

I can't let the system Rescan my 2750 Scans again, because it seems to auto download covers that are already there, like Captain Planet, etc, also gets confused on each entry of my 150 Official CD32 games I have added, which all takes a long time to say ignore on each prompt. Just takes so much time.

**Comment by ransom1122** [comment]
I press No to all 3 options it skipped everything not adding the artwork to 3d world boxing?
I typed 3D World Boxing*
Did the star confuse it?
Will the cover scanner scan ADF games? As 3D world boxing is an adf as their is no whdload version of that game.

**Comment by HoraceAndTheSpider** [comment]
"Overwrite existing images, such as in boxarts/ ? (y/n) "

Select "n" to only download images you do not have.



"Limit scanned files to a specific pattern match? (Enter pattern or leave blank) "

Type the name of the game you want to scan, or parts of the game name to limit to similar results only.



Sent from my iPhone

**Comment by ransom1122** [comment]
At the "Limit scanned files to a specific pattern match? (Enter pattern or leave blank) " part

I entered; 

**3D World Boxing** - DIdnt work

and then I tried

**3D World Boxing [ADF]** - Didnt work

Then said "n" to all the prompts for the scan, and it would not find the cover to this game. yet the cover exists @ Openretro here https://openretro.org/amiga/3d-world-boxing

As a test I deleted Wrath of The Demon WHDLoad Cover as a trial, and rescan the covers again

At the "Limit scanned files to a specific pattern match? (Enter pattern or leave blank) " part I tried typing **Wrath** and it worked. Re scanned only that image.

Is there a problem for it not to scan ADF games and only works WHDLoad games?

**Comment by HoraceAndTheSpider** [comment]
it depends - i assume you still have the file as "3D World Boxing [ADF].uae" ?   or do you only have the .adf file?  .adf files themselves are not scanned.

**Comment by ransom1122** [comment]
I only have the 3D World Boxing [ADF].zip in folder path /home/pi/RetroPie/roms/amiga

ADF's don't require UAE files for Emulation Station.

If I create a 3D World Boxing [ADF].uae then the games entry would be shown twice in Emulation Station one for the ZIP (games) & one for the UAE (config)

Am I missing something here?

I created a new **3D World Boxing [ADF] new.uae** in path /home/pi/RetroPie/roms/amiga
and put the game **3D World Boxing [ADF] new.zip** iin a different folder path then **/home/pi/RetroPie/roms/amiga-data/Games_ADF**.

The game boots fine from the UAE now via Emulation Station.

When I scrape the image with python3

I click,
1st prompt "N"
2nd prompt "Limit scanned files to a specific pattern match? (Enter pattern or leave blank) " I tried "**3D**" also tried "**3D World Boxing**"
3rd & 4th prompt "N"

It skips all existing entries and doesn't find 3D World Boxing?

**Comment by HoraceAndTheSpider** [comment]
Superceded by SkyScrsper project.
